Event.create([
  {title: "Swingers",description: "Swingers City is based on a 1920's golf-club set in the bucolic English countryside. Step into the secret world of our old-school clubhouse, rolling greens, lush foliage and unparalleled hospitality. The venue is just a stone's throw from the Gherkin in the heart of London",url: "https://swingersldn.com/",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "Junk Yard Golf",description: "Welcome to JunkYard Golf Cluf! Home of crazy golf, weid cocktails and all thinks Junk",url: "https://www.junkyardgolfclub.co.uk/london/",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "Omescape (Aldgate)",description: "Premier escape room game in London. Immersive, mind-blowing entertainment - find clues, solve puzzles and escape the room in 60 mins.",url: "https://omescapelondon.co.uk/",location: "London",price_range: 3,category: "Group Fun"},
  {title: "Omescape (Kings Cross)",description: "Premier escape room game in London. Immersive, mind-blowing entertainment - find clues, solve puzzles and escape the room in 60 mins.",url: "https://omescapelondon.co.uk/",location: "London",price_range: 3,category: "Group Fun/Romantic"},
  {title: "Dans le Noir?",description: "Dans le Noir ? (literally : In the Dark ?) is a set of unique human and sensory experiences. It is first a restaurant chain where guests dine in complete darkness served by unexpected guides.",url: "https://www.danslenoir.com/en/welcome/",location: "London",price_range: 5,category: "Group Fun/Romantic"},
  {title: "Bounce Ping Pong",description: "Bounce is Europe's largest purpose-built Social Ping Pong Club, featuring the finest cocktails, and a critically acclaimed Italian pizza restaurant.",url: "https://www.bouncepingpong.com/",location: 'London',price_range: 2,category: 'Group Fun/Romantic'},
  {title: "LoveBox Festival",description: "This two-day fest brings the best new bands and some veterans of alternative music to its new home at Gunnersbury Park.",url: "https://www.timeout.com/london/music/lovebox-2",location: 'London',price_range: 3,category: 'Group Fun'},
  {title: "Silent Disco at The View from The Shard",description: "Join us at the top of the world famous building where three DJs will play the very best in pop, rock and party favourites all through your personal headphones meaning you can listen to your favourite tunes while your friends listen to theirs.",url: "https://www.theviewfromtheshard.com/en/whats-on/events/silent-disco/silent-disco/?gclid=Cj0KCQjwjtLZBRDLARIsAKT6fXyscsfRymOXUw02K4E7f5MQjCVQOZhWTuzxm0syRPMu5sadBNwChJ8aAm9yEALw_wcB",location: 'London',price_range: 4,category: 'Group Fun/Romantic'},
  {title: "Breakfast club",description: "A Bottomless boozing, all singing, all dancing, brunching experience served up by London’s finest Drag Stars and The Breakfast Club.",url: "https://www.thebreakfastclubcafes.com/",location: 'London',price_range: 4,category: 'Group Fun'},
  {title: "FlipOut",description: "London’s biggest trampoline park with something on offer for all ages! Flip Out Wandsworth is based in the ideal location not far from Wimbledon, Clapham and Fulham.",url: "https://www.flipout.co.uk/",location: "London",price_range: 2,category: "Group Fun"},
  {title: "Ballie Ballerson, Bottomless Brunch",description: "Ballie Ballerson is a ball pit cocktail bar with one million balls, retro sweetie cocktails and damn sexy food - Ballie Ballerson is the ultimate adult playground to get loose. The Shoreditch venue provides masses of space and nostalgic hedonism with unparalleled photo opportunities. Two hours of unlimited prosecco and unlimited pizza at the world famous ball pit cocktail bar with one million balls. Enjoy our main glowing ball pit for two hours alongside your prosecco and pizza. ",url: "
https://www.ballieballerson.com/",location: "London",price_range: 3,category: "Group Fun"},
  {title: "Draughts Board Game Cafe",description: "Draughts is London’s first board game café, a haven for game lovers. We have a team of experienced, knowledgeable, and friendly staff to help customers select from a huge library of games – 800+ and counting!We serve high quality food, snacks and a range of local craft beers, ales, ciders, and wines for all those late night sessions.",url: "draughtslondon.com",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "Pottery Painting",description: "Explore your inner Artist at Social Pottery Painting.  We'll guide you through every step of its process.  Paint your own pottery with us in the heart of Camden Town, London or use our mobile services.",url: "https://www.socialpottery.com/",location: "London",price_range: 2,category: "Group Fun"},
  {title: "Hyper Japan",description: "HYPER JAPAN is the largest exhibition celebrating Japanese culture to be held in the UK. Organized by Cross Media Ltd., it was first held in London 2010 and since 2014 has taken place twice a year, in July and November.",url: "https://hyperjapan.co.uk/",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "Seven Noses of London (Walking tour)",description: "Hunting for the ears and noses in Covent Garden and Soho really is terrifc fun and it makes for a great morning, afternoon, or even evening out with friends, family, or even a few random strangers you might happen to encounter in the course (or should that be cause?) of your nose and ear safari.",url: "https://www.london-walking-tours.co.uk/the-seven-noses-of-soho.htm",location: "London",price_range: 1,category: "Group fun/Romantic"},
  {title: "Nandos Recording Studio",description: "All the best ideas start over PERi-PERi (or so we heard). That’s why we’ve brought together two of our favourite things - chicken and tunes - for our first ever restaurant recording studio.  Nestled downstairs in our recently renovated Soho restaurant, the space has been designed for emerging talent to fuel their creativity and collaborate in familiar, relaxing surroundings.",url: "https://www.nandos.co.uk/explore/music/soho-studio",location: "London",price_range: 1,category: "Group Fun/Romantic"},
  {title: "",description: "",url: "",location: "",price_range: ,category: ""},
  {title: "",description: "",url: "",location: "",price_range: ,category: ""},
  ])

Availability.create([
  {date: '2018-07-01'},
  {date: '2018-07-02'},
  {date: '2018-07-03'},
  {date: '2018-07-04'},
  {date: '2018-07-05'},
  {date: '2018-07-06'},
  {date: '2018-07-07'},
  {date: '2018-07-08'},
  {date: '2018-07-09'},
  {date: '2018-07-10'},
  {date: '2018-07-11'},
  {date: '2018-07-12'},
  {date: '2018-07-13'},
  {date: '2018-07-14'},
  {date: '2018-07-15'},
  {date: '2018-07-16'},
  {date: '2018-07-17'},
  {date: '2018-07-18'},
  {date: '2018-07-19'},
  {date: '2018-07-20'},
  {date: '2018-07-21'},
  {date: '2018-07-22'},
  {date: '2018-07-23'},
  {date: '2018-07-24'},
  {date: '2018-07-25'},
  {date: '2018-07-26'},
  {date: '2018-07-27'},
  {date: '2018-07-28'},
  {date: '2018-07-29'},
  {date: '2018-07-30'},
  {date: '2018-07-31'},
])

AvailabilitiesEvent.create([
  {event_id: 1, availability_id: 1},
  {event_id: 1, availability_id: 2},
  {event_id: 1, availability_id: 3},
  {event_id: 1, availability_id: 4},
  {event_id: 1, availability_id: 5},
  {event_id: 1, availability_id: 6},
  {event_id: 1, availability_id: 7},
  {event_id: 1, availability_id: 8},
  {event_id: 1, availability_id: 9},
  {event_id: 1, availability_id: 10},
  {event_id: 1, availability_id: 11},
  {event_id: 1, availability_id: 12},
  {event_id: 1, availability_id: 13},
  {event_id: 1, availability_id: 14},
  {event_id: 1, availability_id: 15},
  {event_id: 1, availability_id: 16},
  {event_id: 1, availability_id: 17},
  {event_id: 1, availability_id: 18},
  {event_id: 1, availability_id: 19},
  {event_id: 1, availability_id: 20},
  {event_id: 1, availability_id: 21},
  {event_id: 1, availability_id: 22},
  {event_id: 1, availability_id: 23},
  {event_id: 1, availability_id: 24},
  {event_id: 1, availability_id: 25},
  {event_id: 1, availability_id: 26},
  {event_id: 1, availability_id: 27},
  {event_id: 1, availability_id: 28},
  {event_id: 1, availability_id: 29},
  {event_id: 1, availability_id: 30},
  {event_id: 1, availability_id: 31},
  {event_id: 2, availability_id: 1},
  {event_id: 2, availability_id: 2},
  {event_id: 2, availability_id: 3},
  {event_id: 2, availability_id: 4},
  {event_id: 2, availability_id: 5},
  {event_id: 2, availability_id: 6},
  {event_id: 2, availability_id: 7},
  {event_id: 2, availability_id: 8},
  {event_id: 2, availability_id: 9},
  {event_id: 2, availability_id: 10},
  {event_id: 2, availability_id: 11},
  {event_id: 2, availability_id: 12},
  {event_id: 2, availability_id: 13},
  {event_id: 2, availability_id: 14},
  {event_id: 2, availability_id: 15},
  {event_id: 2, availability_id: 16},
  {event_id: 2, availability_id: 17},
  {event_id: 2, availability_id: 18},
  {event_id: 2, availability_id: 19},
  {event_id: 2, availability_id: 20},
  {event_id: 2, availability_id: 21},
  {event_id: 2, availability_id: 22},
  {event_id: 2, availability_id: 23},
  {event_id: 2, availability_id: 24},
  {event_id: 2, availability_id: 25},
  {event_id: 2, availability_id: 26},
  {event_id: 2, availability_id: 27},
  {event_id: 2, availability_id: 28},
  {event_id: 2, availability_id: 29},
  {event_id: 2, availability_id: 30},
  {event_id: 2, availability_id: 31},
  {event_id: 3, availability_id: 1},
  {event_id: 3, availability_id: 2},
  {event_id: 3, availability_id: 3},
  {event_id: 3, availability_id: 4},
  {event_id: 3, availability_id: 5},
  {event_id: 3, availability_id: 6},
  {event_id: 3, availability_id: 7},
  {event_id: 3, availability_id: 8},
  {event_id: 3, availability_id: 9},
  {event_id: 3, availability_id: 10},
  {event_id: 3, availability_id: 11},
  {event_id: 3, availability_id: 12},
  {event_id: 3, availability_id: 13},
  {event_id: 3, availability_id: 14},
  {event_id: 3, availability_id: 15},
  {event_id: 3, availability_id: 16},
  {event_id: 3, availability_id: 17},
  {event_id: 3, availability_id: 18},
  {event_id: 3, availability_id: 19},
  {event_id: 3, availability_id: 20},
  {event_id: 3, availability_id: 21},
  {event_id: 3, availability_id: 22},
  {event_id: 3, availability_id: 23},
  {event_id: 3, availability_id: 24},
  {event_id: 3, availability_id: 25},
  {event_id: 3, availability_id: 26},
  {event_id: 3, availability_id: 27},
  {event_id: 3, availability_id: 28},
  {event_id: 3, availability_id: 29},
  {event_id: 3, availability_id: 30},
  {event_id: 3, availability_id: 31},
  {event_id: 4, availability_id: 1},
  {event_id: 4, availability_id: 2},
  {event_id: 4, availability_id: 3},
  {event_id: 4, availability_id: 4},
  {event_id: 4, availability_id: 5},
  {event_id: 4, availability_id: 6},
  {event_id: 4, availability_id: 7},
  {event_id: 4, availability_id: 8},
  {event_id: 4, availability_id: 9},
  {event_id: 4, availability_id: 10},
  {event_id: 4, availability_id: 11},
  {event_id: 4, availability_id: 12},
  {event_id: 4, availability_id: 13},
  {event_id: 4, availability_id: 14},
  {event_id: 4, availability_id: 15},
  {event_id: 4, availability_id: 16},
  {event_id: 4, availability_id: 17},
  {event_id: 4, availability_id: 18},
  {event_id: 4, availability_id: 19},
  {event_id: 4, availability_id: 20},
  {event_id: 4, availability_id: 21},
  {event_id: 4, availability_id: 22},
  {event_id: 4, availability_id: 23},
  {event_id: 4, availability_id: 24},
  {event_id: 4, availability_id: 25},
  {event_id: 4, availability_id: 26},
  {event_id: 4, availability_id: 27},
  {event_id: 4, availability_id: 28},
  {event_id: 4, availability_id: 29},
  {event_id: 4, availability_id: 30},
  {event_id: 4, availability_id: 31},
  {event_id: 5, availability_id: 1},
  {event_id: 5, availability_id: 2},
  {event_id: 5, availability_id: 3},
  {event_id: 5, availability_id: 4},
  {event_id: 5, availability_id: 5},
  {event_id: 5, availability_id: 6},
  {event_id: 5, availability_id: 7},
  {event_id: 5, availability_id: 8},
  {event_id: 5, availability_id: 9},
  {event_id: 5, availability_id: 10},
  {event_id: 5, availability_id: 11},
  {event_id: 5, availability_id: 12},
  {event_id: 5, availability_id: 13},
  {event_id: 5, availability_id: 14},
  {event_id: 5, availability_id: 15},
  {event_id: 5, availability_id: 16},
  {event_id: 5, availability_id: 17},
  {event_id: 5, availability_id: 18},
  {event_id: 5, availability_id: 19},
  {event_id: 5, availability_id: 20},
  {event_id: 5, availability_id: 21},
  {event_id: 5, availability_id: 22},
  {event_id: 5, availability_id: 23},
  {event_id: 5, availability_id: 24},
  {event_id: 5, availability_id: 25},
  {event_id: 5, availability_id: 26},
  {event_id: 5, availability_id: 27},
  {event_id: 5, availability_id: 28},
  {event_id: 5, availability_id: 29},
  {event_id: 5, availability_id: 30},
  {event_id: 5, availability_id: 31},
  {event_id: 6, availability_id: 1},
  {event_id: 6, availability_id: 2},
  {event_id: 6, availability_id: 3},
  {event_id: 6, availability_id: 4},
  {event_id: 6, availability_id: 5},
  {event_id: 6, availability_id: 6},
  {event_id: 6, availability_id: 7},
  {event_id: 6, availability_id: 8},
  {event_id: 6, availability_id: 9},
  {event_id: 6, availability_id: 10},
  {event_id: 6, availability_id: 11},
  {event_id: 6, availability_id: 12},
  {event_id: 6, availability_id: 13},
  {event_id: 6, availability_id: 14},
  {event_id: 6, availability_id: 15},
  {event_id: 6, availability_id: 16},
  {event_id: 6, availability_id: 17},
  {event_id: 6, availability_id: 18},
  {event_id: 6, availability_id: 19},
  {event_id: 6, availability_id: 20},
  {event_id: 6, availability_id: 21},
  {event_id: 6, availability_id: 22},
  {event_id: 6, availability_id: 23},
  {event_id: 6, availability_id: 24},
  {event_id: 6, availability_id: 25},
  {event_id: 6, availability_id: 26},
  {event_id: 6, availability_id: 27},
  {event_id: 6, availability_id: 28},
  {event_id: 6, availability_id: 29},
  {event_id: 6, availability_id: 30},
  {event_id: 6, availability_id: 31},
  {event_id: 7, availability_id: 13},
  {event_id: 7, availability_id: 14},
  {event_id: 8, availability_id: 14},
  {event_id: 9, availability_id: 14},
  {event_id: 10, availability_id: 1},
  {event_id: 10, availability_id: 2},
  {event_id: 10, availability_id: 3},
  {event_id: 10, availability_id: 4},
  {event_id: 10, availability_id: 5},
  {event_id: 10, availability_id: 6},
  {event_id: 10, availability_id: 7},
  {event_id: 10, availability_id: 8},
  {event_id: 10, availability_id: 9},
  {event_id: 10, availability_id: 10},
  {event_id: 10, availability_id: 11},
  {event_id: 10, availability_id: 12},
  {event_id: 10, availability_id: 13},
  {event_id: 10, availability_id: 14},
  {event_id: 10, availability_id: 15},
  {event_id: 10, availability_id: 16},
  {event_id: 10, availability_id: 17},
  {event_id: 10, availability_id: 18},
  {event_id: 10, availability_id: 19},
  {event_id: 10, availability_id: 20},
  {event_id: 10, availability_id: 21},
  {event_id: 10, availability_id: 22},
  {event_id: 10, availability_id: 23},
  {event_id: 10, availability_id: 24},
  {event_id: 10, availability_id: 25},
  {event_id: 10, availability_id: 26},
  {event_id: 10, availability_id: 27},
  {event_id: 10, availability_id: 28},
  {event_id: 10, availability_id: 29},
  {event_id: 10, availability_id: 30},
  {event_id: 10, availability_id: 31},
  {event_id: 11, availability_id: 1},
  {event_id: 11, availability_id: 2},
  {event_id: 11, availability_id: 3},
  {event_id: 11, availability_id: 4},
  {event_id: 11, availability_id: 5},
  {event_id: 11, availability_id: 6},
  {event_id: 11, availability_id: 7},
  {event_id: 11, availability_id: 8},
  {event_id: 11, availability_id: 9},
  {event_id: 11, availability_id: 10},
  {event_id: 11, availability_id: 11},
  {event_id: 11, availability_id: 12},
  {event_id: 11, availability_id: 13},
  {event_id: 11, availability_id: 14},
  {event_id: 11, availability_id: 15},
  {event_id: 11, availability_id: 16},
  {event_id: 11, availability_id: 17},
  {event_id: 11, availability_id: 18},
  {event_id: 11, availability_id: 19},
  {event_id: 11, availability_id: 20},
  {event_id: 11, availability_id: 21},
  {event_id: 11, availability_id: 22},
  {event_id: 11, availability_id: 23},
  {event_id: 11, availability_id: 24},
  {event_id: 11, availability_id: 25},
  {event_id: 11, availability_id: 26},
  {event_id: 11, availability_id: 27},
  {event_id: 11, availability_id: 28},
  {event_id: 11, availability_id: 29},
  {event_id: 11, availability_id: 30},
  {event_id: 11, availability_id: 31},
  {event_id: 12, availability_id: 1},
  {event_id: 12, availability_id: 2},
  {event_id: 12, availability_id: 3},
  {event_id: 12, availability_id: 4},
  {event_id: 12, availability_id: 5},
  {event_id: 12, availability_id: 6},
  {event_id: 12, availability_id: 7},
  {event_id: 12, availability_id: 8},
  {event_id: 12, availability_id: 9},
  {event_id: 12, availability_id: 10},
  {event_id: 12, availability_id: 11},
  {event_id: 12, availability_id: 12},
  {event_id: 12, availability_id: 13},
  {event_id: 12, availability_id: 14},
  {event_id: 12, availability_id: 15},
  {event_id: 12, availability_id: 16},
  {event_id: 12, availability_id: 17},
  {event_id: 12, availability_id: 18},
  {event_id: 12, availability_id: 19},
  {event_id: 12, availability_id: 20},
  {event_id: 12, availability_id: 21},
  {event_id: 12, availability_id: 22},
  {event_id: 12, availability_id: 23},
  {event_id: 12, availability_id: 24},
  {event_id: 12, availability_id: 25},
  {event_id: 12, availability_id: 26},
  {event_id: 12, availability_id: 27},
  {event_id: 12, availability_id: 28},
  {event_id: 12, availability_id: 29},
  {event_id: 12, availability_id: 30},
  {event_id: 12, availability_id: 31},
  {event_id: 13, availability_id: 1},
  {event_id: 13, availability_id: 2},
  {event_id: 13, availability_id: 3},
  {event_id: 13, availability_id: 4},
  {event_id: 13, availability_id: 5},
  {event_id: 13, availability_id: 6},
  {event_id: 13, availability_id: 7},
  {event_id: 13, availability_id: 8},
  {event_id: 13, availability_id: 9},
  {event_id: 13, availability_id: 10},
  {event_id: 13, availability_id: 11},
  {event_id: 13, availability_id: 12},
  {event_id: 13, availability_id: 13},
  {event_id: 13, availability_id: 14},
  {event_id: 13, availability_id: 15},
  {event_id: 13, availability_id: 16},
  {event_id: 13, availability_id: 17},
  {event_id: 13, availability_id: 18},
  {event_id: 13, availability_id: 19},
  {event_id: 13, availability_id: 20},
  {event_id: 13, availability_id: 21},
  {event_id: 13, availability_id: 22},
  {event_id: 13, availability_id: 23},
  {event_id: 13, availability_id: 24},
  {event_id: 13, availability_id: 25},
  {event_id: 13, availability_id: 26},
  {event_id: 13, availability_id: 27},
  {event_id: 13, availability_id: 28},
  {event_id: 13, availability_id: 29},
  {event_id: 13, availability_id: 30},
  {event_id: 13, availability_id: 31},
  {event_id: 14, availability_id: 13},
  {event_id: 14, availability_id: 14},
  {event_id: 14, availability_id: 15},
  {event_id: 15, availability_id: 1},
  {event_id: 15, availability_id: 2},
  {event_id: 15, availability_id: 3},
  {event_id: 15, availability_id: 4},
  {event_id: 15, availability_id: 5},
  {event_id: 15, availability_id: 6},
  {event_id: 15, availability_id: 7},
  {event_id: 15, availability_id: 8},
  {event_id: 15, availability_id: 9},
  {event_id: 15, availability_id: 10},
  {event_id: 15, availability_id: 11},
  {event_id: 15, availability_id: 12},
  {event_id: 15, availability_id: 13},
  {event_id: 15, availability_id: 14},
  {event_id: 15, availability_id: 15},
  {event_id: 15, availability_id: 16},
  {event_id: 15, availability_id: 17},
  {event_id: 15, availability_id: 18},
  {event_id: 15, availability_id: 19},
  {event_id: 15, availability_id: 20},
  {event_id: 15, availability_id: 21},
  {event_id: 15, availability_id: 22},
  {event_id: 15, availability_id: 23},
  {event_id: 15, availability_id: 24},
  {event_id: 15, availability_id: 25},
  {event_id: 15, availability_id: 26},
  {event_id: 15, availability_id: 27},
  {event_id: 15, availability_id: 28},
  {event_id: 15, availability_id: 29},
  {event_id: 15, availability_id: 30},
  {event_id: 15, availability_id: 31},
  {event_id: 16, availability_id: 1},
  {event_id: 16, availability_id: 2},
  {event_id: 16, availability_id: 3},
  {event_id: 16, availability_id: 4},
  {event_id: 16, availability_id: 5},
  {event_id: 16, availability_id: 6},
  {event_id: 16, availability_id: 7},
  {event_id: 16, availability_id: 8},
  {event_id: 16, availability_id: 9},
  {event_id: 16, availability_id: 10},
  {event_id: 16, availability_id: 11},
  {event_id: 16, availability_id: 12},
  {event_id: 16, availability_id: 13},
  {event_id: 16, availability_id: 14},
  {event_id: 16, availability_id: 15},
  {event_id: 16, availability_id: 16},
  {event_id: 16, availability_id: 17},
  {event_id: 16, availability_id: 18},
  {event_id: 16, availability_id: 19},
  {event_id: 16, availability_id: 20},
  {event_id: 16, availability_id: 21},
  {event_id: 16, availability_id: 22},
  {event_id: 16, availability_id: 23},
  {event_id: 16, availability_id: 24},
  {event_id: 16, availability_id: 25},
  {event_id: 16, availability_id: 26},
  {event_id: 16, availability_id: 27},
  {event_id: 16, availability_id: 28},
  {event_id: 16, availability_id: 29},
  {event_id: 16, availability_id: 30},
  {event_id: 16, availability_id: 31},


])
