Event.create([
  {title: "Swingers",description: "Swingers City is based on a 1920's golf-club set in the bucolic English countryside. Step into the secret world of our old-school clubhouse, rolling greens, lush foliage and unparalleled hospitality. The venue is just a stone's throw from the Gherkin in the heart of London",url: "https://swingersldn.com/",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "Junk Yard Golf",description: "Welcome to JunkYard Golf Cluf! Home of crazy golf, weid cocktails and all thinks Junk",url: "https://www.junkyardgolfclub.co.uk/london/",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "Omescape (Aldgate)",description: "Premier escape room game in London. Immersive, mind-blowing entertainment - find clues, solve puzzles and escape the room in 60 mins.",url: "https://omescapelondon.co.uk/",location: "London",price_range: 3,category: "Group Fun"},
  {title: "Omescape (Kings Cross)",description: "Premier escape room game in London. Immersive, mind-blowing entertainment - find clues, solve puzzles and escape the room in 60 mins.",url: "https://omescapelondon.co.uk/",location: "London",price_range: 3,category: "Group Fun/Romantic"},
  {title: "Dans le Noir?",description: "Dans le Noir ? (literally : In the Dark ?) is a set of unique human and sensory experiences. It is first a restaurant chain where guests dine in complete darkness served by unexpected guides.",url: "https://www.danslenoir.com/en/welcome/",location: "London",price_range: 5,category: "Group Fun/Romantic"},
  {title: "Bounce Ping Pong",description: "Bounce is Europe's largest purpose-built Social Ping Pong Club, featuring the finest cocktails, and a critically acclaimed Italian pizza restaurant.",url: "https://www.bouncepingpong.com/",location: 'London',price_range: 2,category: 'Group Fun/Romantic'},
  {title: "LoveBox Festival",description: "This two-day fest brings the best new bands and some veterans of alternative music to its new home at Gunnersbury Park.",url: "https://www.timeout.com/london/music/lovebox-2",location: 'London',price_range: 3,category: 'Group Fun'},
  {title: "Silent Disco at The View from The Shard",description: "Join us at the top of the world famous building where three DJs will play the very best in pop, rock and party favourites all through your personal headphones meaning you can listen to your favourite tunes while your friends listen to theirs.",url: "https://www.theviewfromtheshard.com/en/whats-on/events/silent-disco/silent-disco/?gclid=Cj0KCQjwjtLZBRDLARIsAKT6fXyscsfRymOXUw02K4E7f5MQjCVQOZhWTuzxm0syRPMu5sadBNwChJ8aAm9yEALw_wcB",location: 'London',price_range: 4,category: 'Group Fun/Romantic'},
  {title: "Breakfast club",description: "A Bottomless boozing, all singing, all dancing, brunching experience served up by London’s finest Drag Stars and The Breakfast Club.",url: "https://www.thebreakfastclubcafes.com/",location: 'London',price_range: 4,category: 'Group Fun'},
  {title: "FlipOut",description: "London’s biggest trampoline park with something on offer for all ages! Flip Out Wandsworth is based in the ideal location not far from Wimbledon, Clapham and Fulham.",url: "https://www.flipout.co.uk/",location: "London",price_range: 2,category: "Group Fun"},
  {title: "Ballie Ballerson, Bottomless Brunch",description: "Ballie Ballerson is a ball pit cocktail bar with one million balls, retro sweetie cocktails and damn sexy food - Ballie Ballerson is the ultimate adult playground to get loose. The Shoreditch venue provides masses of space and nostalgic hedonism with unparalleled photo opportunities. Two hours of unlimited prosecco and unlimited pizza at the world famous ball pit cocktail bar with one million balls. Enjoy our main glowing ball pit for two hours alongside your prosecco and pizza. ",url: "
https://www.ballieballerson.com/",location: "London",price_range: 3,category: "Group Fun"},
  {title: "Draughts Board Game Cafe",description: "Draughts is London’s first board game café, a haven for game lovers. We have a team of experienced, knowledgeable, and friendly staff to help customers select from a huge library of games – 800+ and counting!We serve high quality food, snacks and a range of local craft beers, ales, ciders, and wines for all those late night sessions.",url: "draughtslondon.com",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "Pottery Painting",description: "Explore your inner Artist at Social Pottery Painting.  We'll guide you through every step of its process.  Paint your own pottery with us in the heart of Camden Town, London or use our mobile services.",url: "https://www.socialpottery.com/",location: "London",price_range: 2,category: "Group Fun"},
  {title: "Hyper Japan",description: "HYPER JAPAN is the largest exhibition celebrating Japanese culture to be held in the UK. Organized by Cross Media Ltd., it was first held in London 2010 and since 2014 has taken place twice a year, in July and November.",url: "https://hyperjapan.co.uk/",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "Seven Noses of London (Walking tour)",description: "Hunting for the ears and noses in Covent Garden and Soho really is terrifc fun and it makes for a great morning, afternoon, or even evening out with friends, family, or even a few random strangers you might happen to encounter in the course (or should that be cause?) of your nose and ear safari.",url: "https://www.london-walking-tours.co.uk/the-seven-noses-of-soho.htm",location: "London",price_range: 1,category: "Group Fun/Romantic"},
  {title: "Nandos Recording Studio",description: "All the best ideas start over PERi-PERi (or so we heard). That’s why we’ve brought together two of our favourite things - chicken and tunes - for our first ever restaurant recording studio.  Nestled downstairs in our recently renovated Soho restaurant, the space has been designed for emerging talent to fuel their creativity and collaborate in familiar, relaxing surroundings.",url: "https://www.nandos.co.uk/explore/music/soho-studio",location: "London",price_range: 1,category: "Group Fun/Romantic"},
  {title: "God's Own Junkyard",description: "If you’ve been searching for something to brighten up your home, look no further. Gods Own Junkyard is a psychedelic paradise of neon lights and vintage signs, all hidden inside an unassuming warehouse in deepest darkest Walthamstow. Although having said that, all this neon means Walthamstow is dark no more.",url: "https://secretldn.com/gods-own-junkyard-neon-london/",location: "London",price_range: 1,category: "Group Fun/Romantic"},
  {title: "White Water Rafting",description: "You’ll find gallons of fun at Lee Valley White Water Centre, from white water rafting on the Olympic course to family paddling on our lake. Choose from a range of activities or sit back and watch the action at The Terrace Bar & Café; you’re guaranteed an unforgettable day out.",url: "https://www.gowhitewater.co.uk/",location: "London",price_range: 4,category: "Group Fun"},
  {title: "Pride in London",description: "The Pride in London Parade provides a platform for every part of London’s LGBT+ community to raise awareness of LGBT+ issues and campaign for the freedoms that will allow us to live our lives on a genuinely equal footing. ",url: "https://prideinlondon.org/parade/",location: "London",price_range: 1,category: "Group Fun"},
  {title: "Circus",description: "An evening at Circus will take you from drinks, to dining, to dancing and all with a sprinkling of glittering cabaret.",url: "http://www.circus-london.co.uk/",location: "London",price_range: 4,category: "Group Fun"},
  {title: "Go Ape",description: "Our first ever outdoor high ropes course located in the heart of London, Go Ape Battersea takes an urban twist on our classic Tree Top Adventure.",url: "https://goape.co.uk/",location: "London",price_range: 4,category: "Group Fun"},
  {title: "Harry Potter Tour",description: "If you want to see all the Potter-related attractions there are to see in London, you won’t have to look very far. In fact, there are so many Harry Potter attractions in and around London you could be walking past the Ministry of Magic, or The Leaky Cauldron, without even realising it!",url: "https://strawberrytours.com/london/tours/free-harry-potter-tour",location: "London",price_range: 1,category: "Group Fun"},
  {title: "Mad Hatter Afternoon Tea",description: "Fall down the rabbit hole and discover a tea party beyond your wildest imagination. Located in Sanderson’s enchanting Courtyard Terrace, discover a whimsical world to take tea in. Inspired by Alice in Wonderland, expect to meet plenty of familiar characters and recall childhood tales along the way.",url: "https://thecollection.sbe.com/happenings?city=London&hotel=Sanderson&venue=Courtyard+Garden&_ga=2.69458006.713376367.1530103046-1129399839.1530103046",location: "London",price_range: 4,category: "Group Fun"},
  {title: "Jack the Ripper Tour",description: "Discover one of London’s darkest chapters: the shocking murders of Jack the Ripper. This walking tour promises chills and frights as we visit the locations of the Whitechapel Murders, discover more about the victims and the gruesome details of their murders and explore the conspiracy theories surrounding the identity of the killer. Learn about the world’s most chilling, unsolved murder mystery!",url: "https://strawberrytours.com/london/tours/free-jack-the-ripper-tour",location: "London",price_range: 1,category: "Group Fun"},
  {title: "Wigmore Hall, Sunday coffee concert",description: "The perfect way to start your Sunday: listen to an hour of world-class classical music followed by a cup of coffee or a glass of sherry.",url: "https://wigmore-hall.org.uk/wigmore-series/sunday-morning-coffee-concerts?gclid=Cj0KCQjwjtLZBRDLARIsAKT6fXyF2SUJpdzA6pf4tzTIblDwOkU5AR35m5BmpjeinVRM05TdAQ6SUg0aAsqIEALw_wcB",location: "London",price_range: 1,category: "Group Fun/Romantic"},
  {title: "Secret Cinema",description: "Secret Cinema has taken the world of immersive experiences by storm. From grassroots film screenings in abandoned London buildings, to large-scale productions in some of the most spectacular spaces worldwide, we create 360-degree participatory Secret Worlds where the boundaries between performer and audience, set and reality are constantly shifting.",url: "https://tickets.secretcinema.org/index.php",location: "London",price_range: 5,category: "Group Fun/Romantic"},
  {title: "The Mayor of Scardey Cat Town",description: "Cocktails served in a tiny, dimly lit basement bar hidden behind a fridge door in a restaurant.",url: "http://www.themayorofscaredycattown.com/",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "The Discount Suit Company",description: "The Cocktail bar is in what was originally a storeroom for the old suit company above. The bar is named the Discount Suit Company in homage to the existing original sign and business on Pettycoat Lane.",url: "https://discountsuitcompany.co.uk/",location: "London",price_range: 3,category: "Group Fun/Romantic"},
  {title: "The Clink ",description: "Have you ever wondered what it would be like to spend the night locked inside one of the UKs most haunted locations - on the site of "England’s oldest prison"?",url: "https://www.clink.co.uk/paranormal-clink.html",location: "London",price_range: 2,category: "Group Fun"},
  ])

Availability.create([
  {date: '2018-07-01'},
  {date: '2018-07-02'},
  {date: '2018-07-03'},
  {date: '2018-07-04'},
  {date: '2018-07-05'},
  {date: '2018-07-06'},
  {date: '2018-07-07'},
  {date: '2018-07-08'},
  {date: '2018-07-09'},
  {date: '2018-07-10'},
  {date: '2018-07-11'},
  {date: '2018-07-12'},
  {date: '2018-07-13'},
  {date: '2018-07-14'},
  {date: '2018-07-15'},
  {date: '2018-07-16'},
  {date: '2018-07-17'},
  {date: '2018-07-18'},
  {date: '2018-07-19'},
  {date: '2018-07-20'},
  {date: '2018-07-21'},
  {date: '2018-07-22'},
  {date: '2018-07-23'},
  {date: '2018-07-24'},
  {date: '2018-07-25'},
  {date: '2018-07-26'},
  {date: '2018-07-27'},
  {date: '2018-07-28'},
  {date: '2018-07-29'},
  {date: '2018-07-30'},
  {date: '2018-07-31'},
])

AvailabilitiesEvent.create([
  {event_id: 1, availability_id: 1},
  {event_id: 1, availability_id: 2},
  {event_id: 1, availability_id: 3},
  {event_id: 1, availability_id: 4},
  {event_id: 1, availability_id: 5},
  {event_id: 1, availability_id: 6},
  {event_id: 1, availability_id: 7},
  {event_id: 1, availability_id: 8},
  {event_id: 1, availability_id: 9},
  {event_id: 1, availability_id: 10},
  {event_id: 1, availability_id: 11},
  {event_id: 1, availability_id: 12},
  {event_id: 1, availability_id: 13},
  {event_id: 1, availability_id: 14},
  {event_id: 1, availability_id: 15},
  {event_id: 1, availability_id: 16},
  {event_id: 1, availability_id: 17},
  {event_id: 1, availability_id: 18},
  {event_id: 1, availability_id: 19},
  {event_id: 1, availability_id: 20},
  {event_id: 1, availability_id: 21},
  {event_id: 1, availability_id: 22},
  {event_id: 1, availability_id: 23},
  {event_id: 1, availability_id: 24},
  {event_id: 1, availability_id: 25},
  {event_id: 1, availability_id: 26},
  {event_id: 1, availability_id: 27},
  {event_id: 1, availability_id: 28},
  {event_id: 1, availability_id: 29},
  {event_id: 1, availability_id: 30},
  {event_id: 1, availability_id: 31},
  {event_id: 2, availability_id: 1},
  {event_id: 2, availability_id: 2},
  {event_id: 2, availability_id: 3},
  {event_id: 2, availability_id: 4},
  {event_id: 2, availability_id: 5},
  {event_id: 2, availability_id: 6},
  {event_id: 2, availability_id: 7},
  {event_id: 2, availability_id: 8},
  {event_id: 2, availability_id: 9},
  {event_id: 2, availability_id: 10},
  {event_id: 2, availability_id: 11},
  {event_id: 2, availability_id: 12},
  {event_id: 2, availability_id: 13},
  {event_id: 2, availability_id: 14},
  {event_id: 2, availability_id: 15},
  {event_id: 2, availability_id: 16},
  {event_id: 2, availability_id: 17},
  {event_id: 2, availability_id: 18},
  {event_id: 2, availability_id: 19},
  {event_id: 2, availability_id: 20},
  {event_id: 2, availability_id: 21},
  {event_id: 2, availability_id: 22},
  {event_id: 2, availability_id: 23},
  {event_id: 2, availability_id: 24},
  {event_id: 2, availability_id: 25},
  {event_id: 2, availability_id: 26},
  {event_id: 2, availability_id: 27},
  {event_id: 2, availability_id: 28},
  {event_id: 2, availability_id: 29},
  {event_id: 2, availability_id: 30},
  {event_id: 2, availability_id: 31},
  {event_id: 3, availability_id: 1},
  {event_id: 3, availability_id: 2},
  {event_id: 3, availability_id: 3},
  {event_id: 3, availability_id: 4},
  {event_id: 3, availability_id: 5},
  {event_id: 3, availability_id: 6},
  {event_id: 3, availability_id: 7},
  {event_id: 3, availability_id: 8},
  {event_id: 3, availability_id: 9},
  {event_id: 3, availability_id: 10},
  {event_id: 3, availability_id: 11},
  {event_id: 3, availability_id: 12},
  {event_id: 3, availability_id: 13},
  {event_id: 3, availability_id: 14},
  {event_id: 3, availability_id: 15},
  {event_id: 3, availability_id: 16},
  {event_id: 3, availability_id: 17},
  {event_id: 3, availability_id: 18},
  {event_id: 3, availability_id: 19},
  {event_id: 3, availability_id: 20},
  {event_id: 3, availability_id: 21},
  {event_id: 3, availability_id: 22},
  {event_id: 3, availability_id: 23},
  {event_id: 3, availability_id: 24},
  {event_id: 3, availability_id: 25},
  {event_id: 3, availability_id: 26},
  {event_id: 3, availability_id: 27},
  {event_id: 3, availability_id: 28},
  {event_id: 3, availability_id: 29},
  {event_id: 3, availability_id: 30},
  {event_id: 3, availability_id: 31},
  {event_id: 4, availability_id: 1},
  {event_id: 4, availability_id: 2},
  {event_id: 4, availability_id: 3},
  {event_id: 4, availability_id: 4},
  {event_id: 4, availability_id: 5},
  {event_id: 4, availability_id: 6},
  {event_id: 4, availability_id: 7},
  {event_id: 4, availability_id: 8},
  {event_id: 4, availability_id: 9},
  {event_id: 4, availability_id: 10},
  {event_id: 4, availability_id: 11},
  {event_id: 4, availability_id: 12},
  {event_id: 4, availability_id: 13},
  {event_id: 4, availability_id: 14},
  {event_id: 4, availability_id: 15},
  {event_id: 4, availability_id: 16},
  {event_id: 4, availability_id: 17},
  {event_id: 4, availability_id: 18},
  {event_id: 4, availability_id: 19},
  {event_id: 4, availability_id: 20},
  {event_id: 4, availability_id: 21},
  {event_id: 4, availability_id: 22},
  {event_id: 4, availability_id: 23},
  {event_id: 4, availability_id: 24},
  {event_id: 4, availability_id: 25},
  {event_id: 4, availability_id: 26},
  {event_id: 4, availability_id: 27},
  {event_id: 4, availability_id: 28},
  {event_id: 4, availability_id: 29},
  {event_id: 4, availability_id: 30},
  {event_id: 4, availability_id: 31},
  {event_id: 5, availability_id: 1},
  {event_id: 5, availability_id: 2},
  {event_id: 5, availability_id: 3},
  {event_id: 5, availability_id: 4},
  {event_id: 5, availability_id: 5},
  {event_id: 5, availability_id: 6},
  {event_id: 5, availability_id: 7},
  {event_id: 5, availability_id: 8},
  {event_id: 5, availability_id: 9},
  {event_id: 5, availability_id: 10},
  {event_id: 5, availability_id: 11},
  {event_id: 5, availability_id: 12},
  {event_id: 5, availability_id: 13},
  {event_id: 5, availability_id: 14},
  {event_id: 5, availability_id: 15},
  {event_id: 5, availability_id: 16},
  {event_id: 5, availability_id: 17},
  {event_id: 5, availability_id: 18},
  {event_id: 5, availability_id: 19},
  {event_id: 5, availability_id: 20},
  {event_id: 5, availability_id: 21},
  {event_id: 5, availability_id: 22},
  {event_id: 5, availability_id: 23},
  {event_id: 5, availability_id: 24},
  {event_id: 5, availability_id: 25},
  {event_id: 5, availability_id: 26},
  {event_id: 5, availability_id: 27},
  {event_id: 5, availability_id: 28},
  {event_id: 5, availability_id: 29},
  {event_id: 5, availability_id: 30},
  {event_id: 5, availability_id: 31},
  {event_id: 6, availability_id: 1},
  {event_id: 6, availability_id: 2},
  {event_id: 6, availability_id: 3},
  {event_id: 6, availability_id: 4},
  {event_id: 6, availability_id: 5},
  {event_id: 6, availability_id: 6},
  {event_id: 6, availability_id: 7},
  {event_id: 6, availability_id: 8},
  {event_id: 6, availability_id: 9},
  {event_id: 6, availability_id: 10},
  {event_id: 6, availability_id: 11},
  {event_id: 6, availability_id: 12},
  {event_id: 6, availability_id: 13},
  {event_id: 6, availability_id: 14},
  {event_id: 6, availability_id: 15},
  {event_id: 6, availability_id: 16},
  {event_id: 6, availability_id: 17},
  {event_id: 6, availability_id: 18},
  {event_id: 6, availability_id: 19},
  {event_id: 6, availability_id: 20},
  {event_id: 6, availability_id: 21},
  {event_id: 6, availability_id: 22},
  {event_id: 6, availability_id: 23},
  {event_id: 6, availability_id: 24},
  {event_id: 6, availability_id: 25},
  {event_id: 6, availability_id: 26},
  {event_id: 6, availability_id: 27},
  {event_id: 6, availability_id: 28},
  {event_id: 6, availability_id: 29},
  {event_id: 6, availability_id: 30},
  {event_id: 6, availability_id: 31},
  {event_id: 7, availability_id: 13},
  {event_id: 7, availability_id: 14},
  {event_id: 8, availability_id: 14},
  {event_id: 9, availability_id: 14},
  {event_id: 10, availability_id: 1},
  {event_id: 10, availability_id: 2},
  {event_id: 10, availability_id: 3},
  {event_id: 10, availability_id: 4},
  {event_id: 10, availability_id: 5},
  {event_id: 10, availability_id: 6},
  {event_id: 10, availability_id: 7},
  {event_id: 10, availability_id: 8},
  {event_id: 10, availability_id: 9},
  {event_id: 10, availability_id: 10},
  {event_id: 10, availability_id: 11},
  {event_id: 10, availability_id: 12},
  {event_id: 10, availability_id: 13},
  {event_id: 10, availability_id: 14},
  {event_id: 10, availability_id: 15},
  {event_id: 10, availability_id: 16},
  {event_id: 10, availability_id: 17},
  {event_id: 10, availability_id: 18},
  {event_id: 10, availability_id: 19},
  {event_id: 10, availability_id: 20},
  {event_id: 10, availability_id: 21},
  {event_id: 10, availability_id: 22},
  {event_id: 10, availability_id: 23},
  {event_id: 10, availability_id: 24},
  {event_id: 10, availability_id: 25},
  {event_id: 10, availability_id: 26},
  {event_id: 10, availability_id: 27},
  {event_id: 10, availability_id: 28},
  {event_id: 10, availability_id: 29},
  {event_id: 10, availability_id: 30},
  {event_id: 10, availability_id: 31},
  {event_id: 11, availability_id: 1},
  {event_id: 11, availability_id: 2},
  {event_id: 11, availability_id: 3},
  {event_id: 11, availability_id: 4},
  {event_id: 11, availability_id: 5},
  {event_id: 11, availability_id: 6},
  {event_id: 11, availability_id: 7},
  {event_id: 11, availability_id: 8},
  {event_id: 11, availability_id: 9},
  {event_id: 11, availability_id: 10},
  {event_id: 11, availability_id: 11},
  {event_id: 11, availability_id: 12},
  {event_id: 11, availability_id: 13},
  {event_id: 11, availability_id: 14},
  {event_id: 11, availability_id: 15},
  {event_id: 11, availability_id: 16},
  {event_id: 11, availability_id: 17},
  {event_id: 11, availability_id: 18},
  {event_id: 11, availability_id: 19},
  {event_id: 11, availability_id: 20},
  {event_id: 11, availability_id: 21},
  {event_id: 11, availability_id: 22},
  {event_id: 11, availability_id: 23},
  {event_id: 11, availability_id: 24},
  {event_id: 11, availability_id: 25},
  {event_id: 11, availability_id: 26},
  {event_id: 11, availability_id: 27},
  {event_id: 11, availability_id: 28},
  {event_id: 11, availability_id: 29},
  {event_id: 11, availability_id: 30},
  {event_id: 11, availability_id: 31},
  {event_id: 12, availability_id: 1},
  {event_id: 12, availability_id: 2},
  {event_id: 12, availability_id: 3},
  {event_id: 12, availability_id: 4},
  {event_id: 12, availability_id: 5},
  {event_id: 12, availability_id: 6},
  {event_id: 12, availability_id: 7},
  {event_id: 12, availability_id: 8},
  {event_id: 12, availability_id: 9},
  {event_id: 12, availability_id: 10},
  {event_id: 12, availability_id: 11},
  {event_id: 12, availability_id: 12},
  {event_id: 12, availability_id: 13},
  {event_id: 12, availability_id: 14},
  {event_id: 12, availability_id: 15},
  {event_id: 12, availability_id: 16},
  {event_id: 12, availability_id: 17},
  {event_id: 12, availability_id: 18},
  {event_id: 12, availability_id: 19},
  {event_id: 12, availability_id: 20},
  {event_id: 12, availability_id: 21},
  {event_id: 12, availability_id: 22},
  {event_id: 12, availability_id: 23},
  {event_id: 12, availability_id: 24},
  {event_id: 12, availability_id: 25},
  {event_id: 12, availability_id: 26},
  {event_id: 12, availability_id: 27},
  {event_id: 12, availability_id: 28},
  {event_id: 12, availability_id: 29},
  {event_id: 12, availability_id: 30},
  {event_id: 12, availability_id: 31},
  {event_id: 13, availability_id: 1},
  {event_id: 13, availability_id: 2},
  {event_id: 13, availability_id: 3},
  {event_id: 13, availability_id: 4},
  {event_id: 13, availability_id: 5},
  {event_id: 13, availability_id: 6},
  {event_id: 13, availability_id: 7},
  {event_id: 13, availability_id: 8},
  {event_id: 13, availability_id: 9},
  {event_id: 13, availability_id: 10},
  {event_id: 13, availability_id: 11},
  {event_id: 13, availability_id: 12},
  {event_id: 13, availability_id: 13},
  {event_id: 13, availability_id: 14},
  {event_id: 13, availability_id: 15},
  {event_id: 13, availability_id: 16},
  {event_id: 13, availability_id: 17},
  {event_id: 13, availability_id: 18},
  {event_id: 13, availability_id: 19},
  {event_id: 13, availability_id: 20},
  {event_id: 13, availability_id: 21},
  {event_id: 13, availability_id: 22},
  {event_id: 13, availability_id: 23},
  {event_id: 13, availability_id: 24},
  {event_id: 13, availability_id: 25},
  {event_id: 13, availability_id: 26},
  {event_id: 13, availability_id: 27},
  {event_id: 13, availability_id: 28},
  {event_id: 13, availability_id: 29},
  {event_id: 13, availability_id: 30},
  {event_id: 13, availability_id: 31},
  {event_id: 14, availability_id: 13},
  {event_id: 14, availability_id: 14},
  {event_id: 14, availability_id: 15},
  {event_id: 15, availability_id: 1},
  {event_id: 15, availability_id: 2},
  {event_id: 15, availability_id: 3},
  {event_id: 15, availability_id: 4},
  {event_id: 15, availability_id: 5},
  {event_id: 15, availability_id: 6},
  {event_id: 15, availability_id: 7},
  {event_id: 15, availability_id: 8},
  {event_id: 15, availability_id: 9},
  {event_id: 15, availability_id: 10},
  {event_id: 15, availability_id: 11},
  {event_id: 15, availability_id: 12},
  {event_id: 15, availability_id: 13},
  {event_id: 15, availability_id: 14},
  {event_id: 15, availability_id: 15},
  {event_id: 15, availability_id: 16},
  {event_id: 15, availability_id: 17},
  {event_id: 15, availability_id: 18},
  {event_id: 15, availability_id: 19},
  {event_id: 15, availability_id: 20},
  {event_id: 15, availability_id: 21},
  {event_id: 15, availability_id: 22},
  {event_id: 15, availability_id: 23},
  {event_id: 15, availability_id: 24},
  {event_id: 15, availability_id: 25},
  {event_id: 15, availability_id: 26},
  {event_id: 15, availability_id: 27},
  {event_id: 15, availability_id: 28},
  {event_id: 15, availability_id: 29},
  {event_id: 15, availability_id: 30},
  {event_id: 15, availability_id: 31},
  {event_id: 16, availability_id: 1},
  {event_id: 16, availability_id: 2},
  {event_id: 16, availability_id: 3},
  {event_id: 16, availability_id: 4},
  {event_id: 16, availability_id: 5},
  {event_id: 16, availability_id: 6},
  {event_id: 16, availability_id: 7},
  {event_id: 16, availability_id: 8},
  {event_id: 16, availability_id: 9},
  {event_id: 16, availability_id: 10},
  {event_id: 16, availability_id: 11},
  {event_id: 16, availability_id: 12},
  {event_id: 16, availability_id: 13},
  {event_id: 16, availability_id: 14},
  {event_id: 16, availability_id: 15},
  {event_id: 16, availability_id: 16},
  {event_id: 16, availability_id: 17},
  {event_id: 16, availability_id: 18},
  {event_id: 16, availability_id: 19},
  {event_id: 16, availability_id: 20},
  {event_id: 16, availability_id: 21},
  {event_id: 16, availability_id: 22},
  {event_id: 16, availability_id: 23},
  {event_id: 16, availability_id: 24},
  {event_id: 16, availability_id: 25},
  {event_id: 16, availability_id: 26},
  {event_id: 16, availability_id: 27},
  {event_id: 16, availability_id: 28},
  {event_id: 16, availability_id: 29},
  {event_id: 16, availability_id: 30},
  {event_id: 16, availability_id: 31},
  {event_id: 17, availability_id: 1},
  {event_id: 17, availability_id: 2},
  {event_id: 17, availability_id: 3},
  {event_id: 17, availability_id: 8},
  {event_id: 17, availability_id: 9},
  {event_id: 17, availability_id: 10},
  {event_id: 17, availability_id: 15},
  {event_id: 17, availability_id: 16},
  {event_id: 17, availability_id: 17},
  {event_id: 17, availability_id: 22},
  {event_id: 17, availability_id: 23},
  {event_id: 17, availability_id: 24},
  {event_id: 17, availability_id: 29},
  {event_id: 17, availability_id: 30},
  {event_id: 18, availability_id: 1},
  {event_id: 18, availability_id: 2},
  {event_id: 18, availability_id: 3},
  {event_id: 18, availability_id: 4},
  {event_id: 18, availability_id: 5},
  {event_id: 18, availability_id: 6},
  {event_id: 18, availability_id: 7},
  {event_id: 18, availability_id: 8},
  {event_id: 18, availability_id: 9},
  {event_id: 18, availability_id: 10},
  {event_id: 18, availability_id: 11},
  {event_id: 18, availability_id: 12},
  {event_id: 18, availability_id: 13},
  {event_id: 18, availability_id: 14},
  {event_id: 18, availability_id: 15},
  {event_id: 18, availability_id: 16},
  {event_id: 18, availability_id: 17},
  {event_id: 18, availability_id: 18},
  {event_id: 18, availability_id: 19},
  {event_id: 18, availability_id: 20},
  {event_id: 18, availability_id: 21},
  {event_id: 18, availability_id: 22},
  {event_id: 18, availability_id: 23},
  {event_id: 18, availability_id: 24},
  {event_id: 18, availability_id: 25},
  {event_id: 18, availability_id: 26},
  {event_id: 18, availability_id: 27},
  {event_id: 18, availability_id: 28},
  {event_id: 18, availability_id: 29},
  {event_id: 18, availability_id: 30},
  {event_id: 18, availability_id: 31},
  {event_id: 19, availability_id: 7},
  {event_id: 20, availability_id: 2},
  {event_id: 20, availability_id: 3},
  {event_id: 20, availability_id: 4},
  {event_id: 20, availability_id: 5},
  {event_id: 20, availability_id: 6},
  {event_id: 20, availability_id: 7},
  {event_id: 20, availability_id: 10},
  {event_id: 20, availability_id: 11},
  {event_id: 20, availability_id: 12},
  {event_id: 20, availability_id: 13},
  {event_id: 20, availability_id: 14},
  {event_id: 20, availability_id: 17},
  {event_id: 20, availability_id: 18},
  {event_id: 20, availability_id: 19},
  {event_id: 20, availability_id: 20},
  {event_id: 20, availability_id: 21},
  {event_id: 20, availability_id: 24},
  {event_id: 20, availability_id: 25},
  {event_id: 20, availability_id: 26},
  {event_id: 20, availability_id: 27},
  {event_id: 20, availability_id: 28},
  {event_id: 20, availability_id: 31},
  {event_id: 21, availability_id: 1},
  {event_id: 21, availability_id: 2},
  {event_id: 21, availability_id: 3},
  {event_id: 21, availability_id: 4},
  {event_id: 21, availability_id: 5},
  {event_id: 21, availability_id: 6},
  {event_id: 21, availability_id: 7},
  {event_id: 21, availability_id: 8},
  {event_id: 21, availability_id: 9},
  {event_id: 21, availability_id: 10},
  {event_id: 21, availability_id: 11},
  {event_id: 21, availability_id: 12},
  {event_id: 21, availability_id: 13},
  {event_id: 21, availability_id: 14},
  {event_id: 21, availability_id: 15},
  {event_id: 21, availability_id: 16},
  {event_id: 21, availability_id: 17},
  {event_id: 21, availability_id: 18},
  {event_id: 21, availability_id: 19},
  {event_id: 21, availability_id: 20},
  {event_id: 21, availability_id: 21},
  {event_id: 21, availability_id: 22},
  {event_id: 21, availability_id: 23},
  {event_id: 21, availability_id: 24},
  {event_id: 21, availability_id: 25},
  {event_id: 21, availability_id: 26},
  {event_id: 21, availability_id: 27},
  {event_id: 21, availability_id: 28},
  {event_id: 21, availability_id: 29},
  {event_id: 21, availability_id: 30},
  {event_id: 21, availability_id: 31},
  {event_id: 22, availability_id: 1},
  {event_id: 22, availability_id: 2},
  {event_id: 22, availability_id: 3},
  {event_id: 22, availability_id: 4},
  {event_id: 22, availability_id: 5},
  {event_id: 22, availability_id: 6},
  {event_id: 22, availability_id: 7},
  {event_id: 22, availability_id: 8},
  {event_id: 22, availability_id: 9},
  {event_id: 22, availability_id: 10},
  {event_id: 22, availability_id: 11},
  {event_id: 22, availability_id: 12},
  {event_id: 22, availability_id: 13},
  {event_id: 22, availability_id: 14},
  {event_id: 22, availability_id: 15},
  {event_id: 22, availability_id: 16},
  {event_id: 22, availability_id: 17},
  {event_id: 22, availability_id: 18},
  {event_id: 22, availability_id: 19},
  {event_id: 22, availability_id: 20},
  {event_id: 22, availability_id: 21},
  {event_id: 22, availability_id: 22},
  {event_id: 22, availability_id: 23},
  {event_id: 22, availability_id: 24},
  {event_id: 22, availability_id: 25},
  {event_id: 22, availability_id: 26},
  {event_id: 22, availability_id: 27},
  {event_id: 22, availability_id: 28},
  {event_id: 22, availability_id: 29},
  {event_id: 22, availability_id: 30},
  {event_id: 22, availability_id: 31},
  {event_id: 23, availability_id: 1},
  {event_id: 23, availability_id: 2},
  {event_id: 23, availability_id: 3},
  {event_id: 23, availability_id: 4},
  {event_id: 23, availability_id: 5},
  {event_id: 23, availability_id: 6},
  {event_id: 23, availability_id: 7},
  {event_id: 23, availability_id: 8},
  {event_id: 23, availability_id: 9},
  {event_id: 23, availability_id: 10},
  {event_id: 23, availability_id: 11},
  {event_id: 23, availability_id: 12},
  {event_id: 23, availability_id: 13},
  {event_id: 23, availability_id: 14},
  {event_id: 23, availability_id: 15},
  {event_id: 23, availability_id: 16},
  {event_id: 23, availability_id: 17},
  {event_id: 23, availability_id: 18},
  {event_id: 23, availability_id: 19},
  {event_id: 23, availability_id: 20},
  {event_id: 23, availability_id: 21},
  {event_id: 23, availability_id: 22},
  {event_id: 23, availability_id: 23},
  {event_id: 23, availability_id: 24},
  {event_id: 23, availability_id: 25},
  {event_id: 23, availability_id: 26},
  {event_id: 23, availability_id: 27},
  {event_id: 23, availability_id: 28},
  {event_id: 23, availability_id: 29},
  {event_id: 23, availability_id: 30},
  {event_id: 23, availability_id: 31},
  {event_id: 24, availability_id: 1},
  {event_id: 24, availability_id: 7},
  {event_id: 24, availability_id: 8},
  {event_id: 24, availability_id: 14},
  {event_id: 24, availability_id: 15},
  {event_id: 24, availability_id: 21},
  {event_id: 24, availability_id: 22},
  {event_id: 24, availability_id: 28},
  {event_id: 24, availability_id: 29},
  {event_id: 25, availability_id: 1},
  {event_id: 25, availability_id: 8},
  {event_id: 25, availability_id: 15},
  {event_id: 25, availability_id: 22},
  {event_id: 26, availability_id: 8},
  {event_id: 27, availability_id: 1},
  {event_id: 27, availability_id: 2},
  {event_id: 27, availability_id: 3},
  {event_id: 27, availability_id: 4},
  {event_id: 27, availability_id: 5},
  {event_id: 27, availability_id: 6},
  {event_id: 27, availability_id: 7},
  {event_id: 27, availability_id: 8},
  {event_id: 27, availability_id: 9},
  {event_id: 27, availability_id: 10},
  {event_id: 27, availability_id: 11},
  {event_id: 27, availability_id: 12},
  {event_id: 27, availability_id: 13},
  {event_id: 27, availability_id: 14},
  {event_id: 27, availability_id: 15},
  {event_id: 27, availability_id: 16},
  {event_id: 27, availability_id: 17},
  {event_id: 27, availability_id: 18},
  {event_id: 27, availability_id: 19},
  {event_id: 27, availability_id: 20},
  {event_id: 27, availability_id: 21},
  {event_id: 27, availability_id: 22},
  {event_id: 27, availability_id: 23},
  {event_id: 27, availability_id: 24},
  {event_id: 27, availability_id: 25},
  {event_id: 27, availability_id: 26},
  {event_id: 27, availability_id: 27},
  {event_id: 27, availability_id: 28},
  {event_id: 27, availability_id: 29},
  {event_id: 27, availability_id: 30},
  {event_id: 27, availability_id: 31},
  {event_id: 28, availability_id: 1},
  {event_id: 28, availability_id: 2},
  {event_id: 28, availability_id: 3},
  {event_id: 28, availability_id: 4},
  {event_id: 28, availability_id: 5},
  {event_id: 28, availability_id: 6},
  {event_id: 28, availability_id: 7},
  {event_id: 28, availability_id: 8},
  {event_id: 28, availability_id: 9},
  {event_id: 28, availability_id: 10},
  {event_id: 28, availability_id: 11},
  {event_id: 28, availability_id: 12},
  {event_id: 28, availability_id: 13},
  {event_id: 28, availability_id: 14},
  {event_id: 28, availability_id: 15},
  {event_id: 28, availability_id: 16},
  {event_id: 28, availability_id: 17},
  {event_id: 28, availability_id: 18},
  {event_id: 28, availability_id: 19},
  {event_id: 28, availability_id: 20},
  {event_id: 28, availability_id: 21},
  {event_id: 28, availability_id: 22},
  {event_id: 28, availability_id: 23},
  {event_id: 28, availability_id: 24},
  {event_id: 28, availability_id: 25},
  {event_id: 28, availability_id: 26},
  {event_id: 28, availability_id: 27},
  {event_id: 28, availability_id: 28},
  {event_id: 28, availability_id: 29},
  {event_id: 28, availability_id: 30},
  {event_id: 28, availability_id: 31},
  {event_id: 29, availability_id: 1},
  {event_id: 29, availability_id: 2},
  {event_id: 29, availability_id: 3},
  {event_id: 29, availability_id: 4},
  {event_id: 29, availability_id: 5},
  {event_id: 29, availability_id: 6},
  {event_id: 29, availability_id: 7},
  {event_id: 29, availability_id: 8},
  {event_id: 29, availability_id: 9},
  {event_id: 29, availability_id: 10},
  {event_id: 29, availability_id: 11},
  {event_id: 29, availability_id: 12},
  {event_id: 29, availability_id: 13},
  {event_id: 29, availability_id: 14},
  {event_id: 29, availability_id: 15},
  {event_id: 29, availability_id: 16},
  {event_id: 29, availability_id: 17},
  {event_id: 29, availability_id: 18},
  {event_id: 29, availability_id: 19},
  {event_id: 29, availability_id: 20},
  {event_id: 29, availability_id: 21},
  {event_id: 29, availability_id: 22},
  {event_id: 29, availability_id: 23},
  {event_id: 29, availability_id: 24},
  {event_id: 29, availability_id: 25},
  {event_id: 29, availability_id: 26},
  {event_id: 29, availability_id: 27},
  {event_id: 29, availability_id: 28},
  {event_id: 29, availability_id: 29},
  {event_id: 29, availability_id: 30},
  {event_id: 29, availability_id: 31},


])
