Event.create([
  {title: "Swingers",description: "Swingers City is based on a 1920's golf-club set in the bucolic English countryside. Step into the secret world of our old-school clubhouse, rolling greens, lush foliage and unparalleled hospitality. The venue is just a stone's throw from the Gherkin in the heart of London",url: "https://swingersldn.com/",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "Junk Yard Golf",description: "Welcome to JunkYard Golf Cluf! Home of crazy golf, weid cocktails and all thinks Junk",url: "https://www.junkyardgolfclub.co.uk/london/",location: "London",price_range: 2,category: "Group Fun/Romantic"},
  {title: "Omescape (Aldgate)",description: "Premier escape room game in London. Immersive, mind-blowing entertainment - find clues, solve puzzles and escape the room in 60 mins.",url: "https://omescapelondon.co.uk/",location: "London",price_range: 3,category: "Group Fun"},
  {title: "Omescape (Kings Cross)",description: "Premier escape room game in London. Immersive, mind-blowing entertainment - find clues, solve puzzles and escape the room in 60 mins.",url: "https://omescapelondon.co.uk/",location: "London",price_range: 3,category: "Group Fun/Romantic"},
  {title: "Dans le Noir?",description: "Dans le Noir ? (literally : In the Dark ?) is a set of unique human and sensory experiences. It is first a restaurant chain where guests dine in complete darkness served by unexpected guides.",url: "https://www.danslenoir.com/en/welcome/",location: "London",price_range: 5,category: "Group Fun/Romantic"},
  {title: "Bounce Ping Pong",description: "Bounce is Europe's largest purpose-built Social Ping Pong Club, featuring the finest cocktails, and a critically acclaimed Italian pizza restaurant.",url: "https://www.bouncepingpong.com/",location: 'London',price_range: 2,category: 'Group Fun/Romantic'},
  {title: "LoveBox Festival",description: "This two-day fest brings the best new bands and some veterans of alternative music to its new home at Gunnersbury Park",url: "https://www.timeout.com/london/music/lovebox-2",location: 'London',price_range: 3,category: 'Group Fun/Romantic'}
  ])

Availability.create([
  {date: '2018-07-01'},
  {date: '2018-07-02'},
  {date: '2018-07-03'},
  {date: '2018-07-04'},
  {date: '2018-07-05'},
  {date: '2018-07-06'},
  {date: '2018-07-07'},
  {date: '2018-07-08'},
  {date: '2018-07-09'},
  {date: '2018-07-10'},
  {date: '2018-07-11'},
  {date: '2018-07-12'},
  {date: '2018-07-13'},
  {date: '2018-07-14'},
  {date: '2018-07-15'},
  {date: '2018-07-16'},
  {date: '2018-07-17'},
  {date: '2018-07-18'},
  {date: '2018-07-19'},
  {date: '2018-07-20'},
  {date: '2018-07-21'},
  {date: '2018-07-22'},
  {date: '2018-07-23'},
  {date: '2018-07-24'},
  {date: '2018-07-25'},
  {date: '2018-07-26'},
  {date: '2018-07-27'},
  {date: '2018-07-28'},
  {date: '2018-07-29'},
  {date: '2018-07-30'},
  {date: '2018-07-31'},
])

AvailabilitiesEvent.create([
  {event_id: 1, availability_id: 1},
  {event_id: 1, availability_id: 2},
  {event_id: 1, availability_id: 3},
  {event_id: 1, availability_id: 4},
  {event_id: 1, availability_id: 5},
  {event_id: 1, availability_id: 6},
  {event_id: 1, availability_id: 7},
  {event_id: 1, availability_id: 8},
  {event_id: 1, availability_id: 9},
  {event_id: 1, availability_id: 10},
  {event_id: 1, availability_id: 11},
  {event_id: 1, availability_id: 12},
  {event_id: 1, availability_id: 13},
  {event_id: 1, availability_id: 14},
  {event_id: 1, availability_id: 15},
  {event_id: 1, availability_id: 16},
  {event_id: 1, availability_id: 17},
  {event_id: 1, availability_id: 18},
  {event_id: 1, availability_id: 19},
  {event_id: 1, availability_id: 20},
  {event_id: 1, availability_id: 21},
  {event_id: 1, availability_id: 22},
  {event_id: 1, availability_id: 23},
  {event_id: 1, availability_id: 24},
  {event_id: 1, availability_id: 25},
  {event_id: 1, availability_id: 26},
  {event_id: 1, availability_id: 27},
  {event_id: 1, availability_id: 28},
  {event_id: 1, availability_id: 29},
  {event_id: 1, availability_id: 30},
  {event_id: 1, availability_id: 31},
  {event_id: 2, availability_id: 1},
  {event_id: 2, availability_id: 2},
  {event_id: 2, availability_id: 3},
  {event_id: 2, availability_id: 4},
  {event_id: 2, availability_id: 5},
  {event_id: 2, availability_id: 6},
  {event_id: 2, availability_id: 7},
  {event_id: 2, availability_id: 8},
  {event_id: 2, availability_id: 9},
  {event_id: 2, availability_id: 10},
  {event_id: 2, availability_id: 11},
  {event_id: 2, availability_id: 12},
  {event_id: 2, availability_id: 13},
  {event_id: 2, availability_id: 14},
  {event_id: 2, availability_id: 15},
  {event_id: 2, availability_id: 16},
  {event_id: 2, availability_id: 17},
  {event_id: 2, availability_id: 18},
  {event_id: 2, availability_id: 19},
  {event_id: 2, availability_id: 20},
  {event_id: 2, availability_id: 21},
  {event_id: 2, availability_id: 22},
  {event_id: 2, availability_id: 23},
  {event_id: 2, availability_id: 24},
  {event_id: 2, availability_id: 25},
  {event_id: 2, availability_id: 26},
  {event_id: 2, availability_id: 27},
  {event_id: 2, availability_id: 28},
  {event_id: 2, availability_id: 29},
  {event_id: 2, availability_id: 30},
  {event_id: 2, availability_id: 31},
  {event_id: 3, availability_id: 1},
  {event_id: 3, availability_id: 2},
  {event_id: 3, availability_id: 3},
  {event_id: 3, availability_id: 4},
  {event_id: 3, availability_id: 5},
  {event_id: 3, availability_id: 6},
  {event_id: 3, availability_id: 7},
  {event_id: 3, availability_id: 8},
  {event_id: 3, availability_id: 9},
  {event_id: 3, availability_id: 10},
  {event_id: 3, availability_id: 11},
  {event_id: 3, availability_id: 12},
  {event_id: 3, availability_id: 13},
  {event_id: 3, availability_id: 14},
  {event_id: 3, availability_id: 15},
  {event_id: 3, availability_id: 16},
  {event_id: 3, availability_id: 17},
  {event_id: 3, availability_id: 18},
  {event_id: 3, availability_id: 19},
  {event_id: 3, availability_id: 20},
  {event_id: 3, availability_id: 21},
  {event_id: 3, availability_id: 22},
  {event_id: 3, availability_id: 23},
  {event_id: 3, availability_id: 24},
  {event_id: 3, availability_id: 25},
  {event_id: 3, availability_id: 26},
  {event_id: 3, availability_id: 27},
  {event_id: 3, availability_id: 28},
  {event_id: 3, availability_id: 29},
  {event_id: 3, availability_id: 30},
  {event_id: 3, availability_id: 31},
  {event_id: 4, availability_id: 1},
  {event_id: 4, availability_id: 2},
  {event_id: 4, availability_id: 3},
  {event_id: 4, availability_id: 4},
  {event_id: 4, availability_id: 5},
  {event_id: 4, availability_id: 6},
  {event_id: 4, availability_id: 7},
  {event_id: 4, availability_id: 8},
  {event_id: 4, availability_id: 9},
  {event_id: 4, availability_id: 10},
  {event_id: 4, availability_id: 11},
  {event_id: 4, availability_id: 12},
  {event_id: 4, availability_id: 13},
  {event_id: 4, availability_id: 14},
  {event_id: 4, availability_id: 15},
  {event_id: 4, availability_id: 16},
  {event_id: 4, availability_id: 17},
  {event_id: 4, availability_id: 18},
  {event_id: 4, availability_id: 19},
  {event_id: 4, availability_id: 20},
  {event_id: 4, availability_id: 21},
  {event_id: 4, availability_id: 22},
  {event_id: 4, availability_id: 23},
  {event_id: 4, availability_id: 24},
  {event_id: 4, availability_id: 25},
  {event_id: 4, availability_id: 26},
  {event_id: 4, availability_id: 27},
  {event_id: 4, availability_id: 28},
  {event_id: 4, availability_id: 29},
  {event_id: 4, availability_id: 30},
  {event_id: 4, availability_id: 31},
  {event_id: 5, availability_id: 1},
  {event_id: 5, availability_id: 2},
  {event_id: 5, availability_id: 3},
  {event_id: 5, availability_id: 4},
  {event_id: 5, availability_id: 5},
  {event_id: 5, availability_id: 6},
  {event_id: 5, availability_id: 7},
  {event_id: 5, availability_id: 8},
  {event_id: 5, availability_id: 9},
  {event_id: 5, availability_id: 10},
  {event_id: 5, availability_id: 11},
  {event_id: 5, availability_id: 12},
  {event_id: 5, availability_id: 13},
  {event_id: 5, availability_id: 14},
  {event_id: 5, availability_id: 15},
  {event_id: 5, availability_id: 16},
  {event_id: 5, availability_id: 17},
  {event_id: 5, availability_id: 18},
  {event_id: 5, availability_id: 19},
  {event_id: 5, availability_id: 20},
  {event_id: 5, availability_id: 21},
  {event_id: 5, availability_id: 22},
  {event_id: 5, availability_id: 23},
  {event_id: 5, availability_id: 24},
  {event_id: 5, availability_id: 25},
  {event_id: 5, availability_id: 26},
  {event_id: 5, availability_id: 27},
  {event_id: 5, availability_id: 28},
  {event_id: 5, availability_id: 29},
  {event_id: 5, availability_id: 30},
  {event_id: 5, availability_id: 31},
  {event_id: 6, availability_id: 1},
  {event_id: 6, availability_id: 2},
  {event_id: 6, availability_id: 3},
  {event_id: 6, availability_id: 4},
  {event_id: 6, availability_id: 5},
  {event_id: 6, availability_id: 6},
  {event_id: 6, availability_id: 7},
  {event_id: 6, availability_id: 8},
  {event_id: 6, availability_id: 9},
  {event_id: 6, availability_id: 10},
  {event_id: 6, availability_id: 11},
  {event_id: 6, availability_id: 12},
  {event_id: 6, availability_id: 13},
  {event_id: 6, availability_id: 14},
  {event_id: 6, availability_id: 15},
  {event_id: 6, availability_id: 16},
  {event_id: 6, availability_id: 17},
  {event_id: 6, availability_id: 18},
  {event_id: 6, availability_id: 19},
  {event_id: 6, availability_id: 20},
  {event_id: 6, availability_id: 21},
  {event_id: 6, availability_id: 22},
  {event_id: 6, availability_id: 23},
  {event_id: 6, availability_id: 24},
  {event_id: 6, availability_id: 25},
  {event_id: 6, availability_id: 26},
  {event_id: 6, availability_id: 27},
  {event_id: 6, availability_id: 28},
  {event_id: 6, availability_id: 29},
  {event_id: 6, availability_id: 30},
  {event_id: 6, availability_id: 31},
  {event_id: 7, availability_id: 13},
  {event_id: 7, availability_id: 14},

])
